services:
  # --- Service Base de Données MySQL ---
  bmo-db:
    image: mysql:8.3
    container_name: bmo_base_de_donnees_conteneur
    restart: unless-stopped
    ports:
      - "${BMO_DB_PORT_HOST:-3307}:3306"
    environment:
      MYSQL_DATABASE: ${BMO_DB_NAME:-bmo_base_de_donnees}
      MYSQL_USER: ${BMO_DB_USER:-bmo_utilisateur_app}
      MYSQL_PASSWORD: ${BMO_DB_PASSWORD:-MotDePasseUtilisateurAppFort!}
      MYSQL_ROOT_PASSWORD: ${BMO_DB_ROOT_PASSWORD:-MotDePasseRootFort!}
    volumes:
      - bmo_donnees_mysql_volume:/var/lib/mysql
      - ./bmo-serveur/src/main/resources/sql/schema-initial.sql:/docker-entrypoint-initdb.d/10-schema-initial.sql
    networks:
      - bmo_reseau_interne
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u${BMO_DB_USER:-bmo_utilisateur_app}", "-p${BMO_DB_PASSWORD:-MotDePasseUtilisateurAppFort!}"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

  # --- Service Application Serveur BMO ---
  bmo-serveur-app:
    build:
      context: .
      dockerfile: bmo-serveur/Dockerfile
    container_name: bmo_serveur_conteneur
    restart: unless-stopped
    depends_on:
      bmo-db:
        condition: service_healthy
    ports:
      - "${BMO_SERVER_PORT_HOST:-5000}:${BMO_SERVER_PORT_CONTAINER:-5000}"
    environment:
      BMO_DB_URL: jdbc:mysql://bmo-db:3306/${BMO_DB_NAME:-bmo_base_de_donnees}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&autoReconnect=true
      BMO_DB_UTILISATEUR: ${BMO_DB_USER:-bmo_utilisateur_app}
      BMO_DB_MOTDEPASSE: ${BMO_DB_PASSWORD:-MotDePasseUtilisateurAppFort!}
      BMO_SERVEUR_PORT: ${BMO_SERVER_PORT_CONTAINER:-5000}
    networks:
      - bmo_reseau_interne

  # --- Service PhpMyAdmin ---
  bmo-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: bmo_phpmyadmin_conteneur
    restart: unless-stopped
    depends_on:
      - bmo-db
    ports:
      - "${BMO_PHPMYADMIN_PORT_HOST:-8081}:80"
    environment:
      PMA_HOST: bmo-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${BMO_DB_ROOT_PASSWORD:-MotDePasseRootFort!}
      UPLOAD_LIMIT: 1G
    networks:
      - bmo_reseau_interne

  # --- Service Application Client BMO (JavaFX) ---
  bmo-client-app:
    build:
      context: ./bmo-client  # <--- CONTEXTE MODIFIÉ ICI
      dockerfile: bmo-client/Dockerfile    # <--- Dockerfile est maintenant à la racine de ce nouveau contexte (bmo-client/Dockerfile)
    container_name: bmo_client_conteneur
    restart: "no"
    depends_on:
      - bmo-serveur-app
    environment:
      - DISPLAY=${DISPLAY}
      - BMO_SERVER_ADDRESS=bmo-serveur-app
      - BMO_SERVER_PORT=${BMO_SERVER_PORT_CONTAINER:-5000}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - bmo_reseau_interne

networks:
  bmo_reseau_interne:
    driver: bridge
    name: bmo_reseau_global

volumes:
  bmo_donnees_mysql_volume:
    driver: local