package akandan.bahou.kassy.commun.protocole;

public enum TypeRequeteClient {
    CONNEXION,
    INSCRIPTION,
    DECONNEXION,
    NOUVELLE_REUNION,
    OBTENIR_REUNIONS,
    REJOINDRE_REUNION,
    QUITTER_REUNION,
    MESSAGE_CHAT,
    CLOTURER_REUNION,
    ADMIN_OBTENIR_UTILISATEURS,
    ADMIN_CREER_UTILISATEUR,
    ADMIN_MODIFIER_UTILISATEUR,
    ADMIN_SUPPRIMER_UTILISATEUR,
    ADMIN_OBTENIR_CONFIG,
    ADMIN_DEFINIR_CONFIG,
    OBTENIR_MES_REUNIONS,
    OBTENIR_DETAILS_REUNION,
    OBTENIR_HISTORIQUE_MESSAGES,
    OUVRIR_REUNION,
    CHANGER_MOT_DE_PASSE,
    OBTENIR_MON_PROFIL,
    MODIFIER_PROFIL;
}