package akandan.bahou.kassy.commun.protocole;

public enum TypeReponseServeur {
    AUTH_OK("AUTH_OK"),
    AUTH_ECHEC("AUTH_ECHEC"),
    INSCRIPTION_OK("INSCRIPTION_OK"),
    INSCRIPTION_ECHEC("INSCRIPTION_ECHEC"),
    OPERATION_OK("OPERATION_OK"),
    ERREUR("ERREUR"),
    LISTE_REUNIONS("LISTE_REUNIONS"),
    LISTE_MES_REUNIONS("LISTE_MES_REUNIONS"),
    DETAILS_REUNION("DETAILS_REUNION"),
    REUNION_CREEE("REUNION_CREEE"),
    REUNION_MODIFIEE("REUNION_MODIFIEE"),
    REUNION_OUVERTE("REUNION_OUVERTE"),
    REUNION_CLOTUREE("REUNION_CLOTUREE"),
    REUNION_SUPPRIMEE("REUNION_SUPPRIMEE"),
    REJOINDRE_OK("REJOINDRE_OK"),
    REJOINDRE_ECHEC("REJOINDRE_ECHEC"),
    NOUVEAU_MESSAGE_CHAT("NOUVEAU_MESSAGE_CHAT"),
    HISTORIQUE_MESSAGES("HISTORIQUE_MESSAGES"),
    UTILISATEUR_REJOINT_REUNION("UTILISATEUR_REJOINT_REUNION"),
    UTILISATEUR_QUITTE_REUNION("UTILISATEUR_QUITTE_REUNION"),
    DEMANDE_PAROLE_RECUE("DEMANDE_PAROLE_RECUE"),
    PAROLE_ACCORDEE("PAROLE_ACCORDEE"),
    PAROLE_REFUSEE("PAROLE_REFUSEE"),
    NOTIFICATION_GENERALE("NOTIFICATION_GENERALE"),
    NOTIFICATION_REUNION_CLOTUREE("NOTIFICATION_REUNION_CLOTUREE"),
    DONNEES_UTILISATEUR("DONNEES_UTILISATEUR"),
    LISTE_UTILISATEURS("LISTE_UTILISATEURS"),
    ADMIN_UTILISATEUR_CREE("ADMIN_UTILISATEUR_CREE"),
    ADMIN_UTILISATEUR_MODIFIE("ADMIN_UTILISATEUR_MODIFIE"),
    ADMIN_UTILISATEUR_SUPPRIME("ADMIN_UTILISATEUR_SUPPRIME"),
    ADMIN_CONFIG_RECUE("ADMIN_CONFIG_RECUE"),
    ADMIN_CONFIG_MODIFIEE("ADMIN_CONFIG_MODIFIEE"),
    QUITTER_OK("QUITTER_OK"),
    QUITTER_ECHEC("QUITTER_ECHEC"),
    PROFIL_MODIFIE_OK("PROFIL_MODIFIE_OK"),
    MOT_DE_PASSE_MODIFIE_OK("MOT_DE_PASSE_MODIFIE_OK"),
    ADMIN_CONFIG_LISTE("ADMIN_CONFIG_LISTE")
    ;

    private final String valeurProtocole;

    TypeReponseServeur(String valeurProtocole) {
        this.valeurProtocole = valeurProtocole;
    }

    public String getValeurProtocole() {
        return valeurProtocole;
    }
}