package akandan.bahou.kassy.commun.protocole;

public enum TypeReponseServeur {
    ERREUR("ERREUR"),
    AUTH_OK("AUTH_OK"),
    AUTH_ECHEC("AUTH_ECHEC"),
    INSCRIPTION_OK("INSCRIPTION_OK"),
    INSCRIPTION_ECHEC("INSCRIPTION_ECHEC"),
    REUNION_CREEE("REUNION_CREEE"),
    LISTE_REUNIONS("LISTE_REUNIONS"),
    REJOINDRE_OK("REJOINDRE_OK"),
    REJOINDRE_ECHEC("REJOINDRE_ECHEC"),
    NOUVEAU_MESSAGE_CHAT("NOUVEAU_MESSAGE_CHAT"),
    UTILISATEUR_REJOINT_REUNION("UTILISATEUR_REJOINT_REUNION"),
    UTILISATEUR_QUITTE_REUNION("UTILISATEUR_QUITTE_REUNION"),
    OPERATION_OK("OPERATION_OK"),
    NOTIFICATION_REUNION_CLOTUREE("NOTIFICATION_REUNION_CLOTUREE"),
    REUNION_TERMINEE("REUNION_TERMINEE"),
    LISTE_MES_REUNIONS("LISTE_MES_REUNIONS"),
    DETAILS_REUNION("DETAILS_REUNION"),
    QUITTER_OK("QUITTER_OK"),
    QUITTER_ECHEC("QUITTER_ECHEC"),
    HISTORIQUE_MESSAGES("HISTORIQUE_MESSAGES"),
    REUNION_OUVERTE("REUNION_OUVERTE"),
    REUNION_CLOTUREE("REUNION_CLOTUREE"),
    PROFIL_MODIFIE_OK("PROFIL_MODIFIE_OK"),
    MOT_DE_PASSE_MODIFIE_OK("MOT_DE_PASSE_MODIFIE_OK"),
    DONNEES_UTILISATEUR("DONNEES_UTILISATEUR"),
    ADMIN_UTILISATEUR_CREE("ADMIN_UTILISATEUR_CREE"),
    ADMIN_UTILISATEUR_MODIFIE("ADMIN_UTILISATEUR_MODIFIE"),
    ADMIN_UTILISATEUR_SUPPRIME("ADMIN_UTILISATEUR_SUPPRIME"),
    ADMIN_CONFIG_LISTE("ADMIN_CONFIG_LISTE"),
    ADMIN_CONFIG_MODIFIEE("ADMIN_CONFIG_MODIFIEE"),
    REUNION_MODIFIEE("REUNION_MODIFIEE"),
    LISTE_UTILISATEURS_ADMIN("LISTE_UTILISATEURS_ADMIN"), // Si différent de LISTE_UTILISATEURS
    UTILISATEUR_MODIFIE_ADMIN("UTILISATEUR_MODIFIE_ADMIN"),
    LISTE_UTILISATEURS("LISTE_UTILISATEURS");


    private final String valeurProtocole;

    TypeReponseServeur(String valeurProtocole) {
        this.valeurProtocole = valeurProtocole;
    }

    public String getValeurProtocole() {
        return valeurProtocole;
    }
}